server:
  wechatAPPID: ""
  wechatSecret: ""
  oauth: ""
  wechatRedirect: ""
  JWTSecret: ""
  AESSecret: "" # AES 加密密钥
  port: "8089"
  debug: true

frontend:
  url: ""

database:
  host: ""
  user: ""
  passport: ""
  port: ""
  name: ""
  need: false

startDate: "2021-11-01 00:00:00"  # 报名开始的日期
expiredDate: "2021-11-10 00:00:00" # 报名结束的日期

teamUpperLimit: # 每天的团队上限
  zhAll: # 朝晖校区全程
    0: 150
    1: 100
    2: 100
    3: 150
  pfHalf: # 屏峰校区半程
    0: 180
    1: 120
    2: 120
    3: 180
  pfAll: # 屏峰校区全程
    0: 99
    1: 66
    2: 66
    3: 99
  mgsHalf: # 莫干山校区半程
    0: 100
    1: 75
    2: 75
    3: 100
  mgsAll: # 莫干山校区全程
    0: 50
    1: 25
    2: 25
    3: 50
